services:
  web:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - .:/rails
    command: ./bin/rails server -b 0.0.0.0

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: redis:7.4
    volumes:
      - redis_data:/data

  sidekiq:
    build: .
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - .:/rails
    command: bundle exec sidekiq

volumes:
  postgres_data:
  redis_data: